import XCTest

@testable import MacPower

/// The macOS 27 per-core power model: parsing, DVFS tables, activity and calibration.
final class CorePowerModelTests: XCTestCase {

    // MARK: IOReport names and units

    func testStateIndex() {
        XCTAssertEqual(CorePowerModel.stateIndex("V14P0"), 14)
        XCTAssertEqual(CorePowerModel.stateIndex("V0P4"), 0)
        XCTAssertNil(CorePowerModel.stateIndex("IDLE"))
        XCTAssertNil(CorePowerModel.stateIndex("OFF"))
        XCTAssertNil(CorePowerModel.stateIndex("VP"))
    }

    func testCoreChannelParsing() {
        XCTAssertTrue(CorePowerModel.parseCoreChannel("ECPU010")! == (.efficiency, 0, 1))
        XCTAssertTrue(CorePowerModel.parseCoreChannel("PCPU120")! == (.performance, 1, 2))
        XCTAssertNil(CorePowerModel.parseCoreChannel("ECPU"))
        XCTAssertNil(CorePowerModel.parseCoreChannel("GPUPH0"))
    }

    func testTickRate() {
        XCTAssertEqual(CorePowerModel.tickRate(unitLabel: "24Mticks"), 24e6)
        XCTAssertEqual(CorePowerModel.tickRate(unitLabel: ""), 24e6)
    }

    // MARK: DVFS tables

    private func data(_ pairs: [(UInt32, UInt32)]) -> Data {
        var bytes = Data()
        for (a, b) in pairs {
            withUnsafeBytes(of: a.littleEndian) { bytes.append(contentsOf: $0) }
            withUnsafeBytes(of: b.littleEndian) { bytes.append(contentsOf: $0) }
        }
        return bytes
    }

    func testParsesM1StyleTables() {
        // voltage-states1-sram (Hz, SRAM mV) + voltage-states1 (divider, core mV), as on an M1 Pro.
        let table = DVFSTable.parse(
            frequencies: data([(600_000_000, 565), (972_000_000, 565)]),
            voltages: data([(109_226, 550), (67_423, 609)]))
        XCTAssertEqual(table, DVFSTable(megahertz: [600, 972], millivolts: [550, 609]))
    }

    func testParsesKilohertzAndRejectsNonFrequencyTables() {
        let khz = DVFSTable.parse(frequencies: data([(600_000, 565), (972_000, 600)]), voltages: nil)
        XCTAssertEqual(khz, DVFSTable(megahertz: [600, 972], millivolts: [565, 600]))
        // The plain M1 table's first field falls — it isn't a frequency.
        XCTAssertNil(DVFSTable.parse(frequencies: data([(109_226, 550), (67_423, 609)]), voltages: nil))
    }

    func testTableSelection() {
        func table(_ n: Int, max: Double) -> DVFSTable {
            DVFSTable(
                megahertz: (1...n).map { Double($0) * max / Double(n) },
                millivolts: Array(repeating: 800, count: n))
        }
        let m1Pro = [
            1: table(5, max: 2064), 5: table(15, max: 3228), 13: table(15, max: 3228),
            14: table(7, max: 1296),
        ]
        XCTAssertEqual(
            CorePowerModel.tableNumber(cluster: .efficiency, clusterIndex: 0, states: 5, tables: m1Pro), 1)
        XCTAssertEqual(
            CorePowerModel.tableNumber(cluster: .performance, clusterIndex: 0, states: 15, tables: m1Pro), 5)
        XCTAssertEqual(
            CorePowerModel.tableNumber(cluster: .performance, clusterIndex: 1, states: 15, tables: m1Pro), 13)

        // Unknown layout: fall back to the fastest table with a matching state count.
        let other = [3: table(6, max: 2400), 8: table(6, max: 1500), 9: table(19, max: 4400)]
        XCTAssertEqual(
            CorePowerModel.tableNumber(cluster: .efficiency, clusterIndex: 0, states: 6, tables: other), 3)
        XCTAssertEqual(
            CorePowerModel.tableNumber(cluster: .performance, clusterIndex: 0, states: 19, tables: other), 9)
        XCTAssertNil(
            CorePowerModel.tableNumber(cluster: .performance, clusterIndex: 0, states: 12, tables: other))
    }

    // MARK: Activity

    func testActivityIsSecondsTimesGHzTimesVoltsSquared() {
        let table = DVFSTable(megahertz: [1000, 2000], millivolts: [1000, 500])
        let activity = CorePowerModel.activity(
            residencyDeltas: [("IDLE", 48_000_000), ("V0P1", 24_000_000), ("V1P0", 24_000_000)],
            table: table, tickRate: 24e6)
        // 1 s × 1 GHz × 1 V² + 1 s × 2 GHz × 0.25 V²; IDLE contributes nothing.
        XCTAssertEqual(activity, 1.5, accuracy: 1e-12)
    }

    // MARK: Estimation and calibration

    private let e = { (a: Double) in CoreActivity(label: "E0", cluster: .efficiency, activity: a) }
    private let p = { (a: Double) in CoreActivity(label: "P0", cluster: .performance, activity: a) }

    func testEstimateAppliesConstantsAndOverhead() {
        var model = CorePowerModel(calibration: .init(kE: 0.2, kP: 0.7, overhead: 0.2, batches: 0))
        let result = model.estimate([e(1), p(2)], seconds: 1)
        XCTAssertEqual(result.cores[0], 0.2, accuracy: 1e-12)
        XCTAssertEqual(result.cores[1], 1.4, accuracy: 1e-12)
        XCTAssertEqual(result.cpuWatts, 1.6 * 1.2, accuracy: 1e-12)
    }

    /// Feeds `ticks` one-second ticks, then a batch generated by a "true" model.
    private func runBatch(
        _ model: inout CorePowerModel, ticks: Int, interval: TimeInterval,
        kE: Double = 0.3, kP: Double = 1.0, overhead: Double = 0.25
    ) -> Bool {
        for _ in 0..<ticks { _ = model.estimate([e(0.5), p(2)], seconds: 1) }
        // macOS's batch covers the whole interval at the same activity rate.
        let eJ = kE * 0.5 * interval
        let pJ = kP * 2 * interval
        return model.calibrate(
            with: .init(
                interval: interval, eCoreJoules: eJ, pCoreJoules: pJ, cpuJoules: (eJ + pJ) * (1 + overhead)))
    }

    func testFirstBatchReplacesDefaults() {
        var model = CorePowerModel()
        XCTAssertTrue(runBatch(&model, ticks: 100, interval: 100))
        XCTAssertEqual(model.calibration.kE, 0.3, accuracy: 1e-9)
        XCTAssertEqual(model.calibration.kP, 1.0, accuracy: 1e-9)
        XCTAssertEqual(model.calibration.overhead, 0.25, accuracy: 1e-9)
        XCTAssertTrue(model.isCalibrated)
    }

    func testPartialCoverageIsExtrapolated() {
        var model = CorePowerModel()
        // Launched halfway through macOS's batch interval.
        XCTAssertTrue(runBatch(&model, ticks: 50, interval: 100))
        XCTAssertEqual(model.calibration.kE, 0.3, accuracy: 1e-9)
        XCTAssertEqual(model.calibration.kP, 1.0, accuracy: 1e-9)
    }

    func testTooLittleCoverageIsSkippedButResets() {
        var model = CorePowerModel()
        XCTAssertFalse(runBatch(&model, ticks: 10, interval: 100))
        XCTAssertEqual(model.calibration, .defaults)
        // The next batch starts from a clean slate.
        XCTAssertTrue(runBatch(&model, ticks: 100, interval: 100))
        XCTAssertEqual(model.calibration.kP, 1.0, accuracy: 1e-9)
    }

    func testGapSkipsCalibration() {
        var model = CorePowerModel()
        _ = model.estimate([e(0.5), p(2)], seconds: 30)  // the Mac stalled mid-interval
        XCTAssertFalse(runBatch(&model, ticks: 100, interval: 130))
        XCTAssertFalse(model.isCalibrated)
    }

    func testLaterBatchesBlend() {
        var model = CorePowerModel()
        XCTAssertTrue(runBatch(&model, ticks: 100, interval: 100, kP: 1.0))
        XCTAssertTrue(runBatch(&model, ticks: 100, interval: 100, kP: 2.0))
        XCTAssertEqual(model.calibration.kP, 1.0 + CorePowerModel.blendWeight * 1.0, accuracy: 1e-9)
        XCTAssertEqual(model.calibration.batches, 2)
    }

    func testImplausibleBatchIsRejected() {
        var model = CorePowerModel()
        XCTAssertFalse(runBatch(&model, ticks: 100, interval: 100, kE: -1))
        XCTAssertEqual(model.calibration, .defaults)
    }

    // MARK: Counter cadence

    func testBatchedDetection() {
        XCTAssertFalse(IOReportSampler.isBatched(lastUpdateInterval: nil, age: 0.5))
        XCTAssertTrue(IOReportSampler.isBatched(lastUpdateInterval: nil, age: 600))
        // A known live cadence wins over a momentarily stale value, and vice versa.
        XCTAssertFalse(IOReportSampler.isBatched(lastUpdateInterval: 1, age: 45))
        XCTAssertTrue(IOReportSampler.isBatched(lastUpdateInterval: 1100, age: 2))
    }
}
